export const sagaActions = {
  LOGOUT: "LOGOUT",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  GET_USER: "GET_USER",
  ONBOARD_USER: "ONBOARD_USER",
  FETCH_WEIGHT_HISTORY: "FETCH_WEIGHT_HISTORY",
  ADD_WEIGHT: "ADD_WEIGHT",
  ADD_WORKOUT: "ADD_WORKOUT",
  FETCH_WORKOUT: "FETCH_WORKOUT",
  FETCH_MEAL_OPTIONS: "FETCH_MEAL_OPTIONS",
  FETCH_TOTAL_DAY_CALORIES: "FETCH_TOTAL_DAY_CALORIES",
  FETCH_TODAY_MEALS: "FETCH_TODAY_MEALS",
};
