export const sagaActions = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  GET_USER: "GET_USER",
  ONBOARD_USER: "ONBOARD_USER",
  FETCH_WEIGHT_HISTORY: "FETCH_WEIGHT_HISTORY",
  ADD_WEIGHT: "ADD_WEIGHT",
  FETCH_MEAL_OPTIONS: "FETCH_MEAL_OPTIONS",
  FETCH_TOTAL_DAY_CALORIES: "FETCH_TOTAL_DAY_CALORIES",
  //   ADD_MEAL: "ADD_MEAL",
};
